### ISSUE TITLE
Encode Formulas to prevent CSV injection

### ISSUE THREAD

**Issue by maennchen** [beatrichartz/csv#103]
**If this is a feature request, why do we need it?**

- We are using this library to generate CSVs for user-generated input and transmitting them to another party. (Which sadly requires a CSV and not a sane format like a JSON)
- We did a pentest on the application
  - Security Advisory: https://github.com/jshmrtn/hygeia/security/advisories/GHSA-8pwv-jhj2-2369
- The pentest uncovered a [CSV Injection vulnerability](https://owasp.org/www-community/attacks/CSV_Injection), if the user-generated input includes formulas like `=1+1`

To address this, I suggest to implement encoding of `=1+1` as `"'=1+1"`

**If this is a bug, steps to reproduce it**
- Generate a CSV with a cell value of `=1+1`
- Open with Excel
- See value `2`
- Is your input CSV [RFC 4180](https://tools.ietf.org/html/rfc4180) compliant? - Yes
- Are you interested in helping with a PR? - Yes

**Comment by beatrichartz** [comment]
PR is merged, thanks
