### ISSUE TITLE
v3.0.1 module documentation missing on hexdocs.pm

### ISSUE THREAD

**Issue by superhawk610** [beatrichartz/csv#114]
The module documentation, typically found under [API Reference](https://hexdocs.pm/csv/3.0.1/api-reference.html) on hexdocs.pm appears to be missing on the latest version. It is present on [v3.0.0](https://hexdocs.pm/csv/3.0.0/api-reference.html) and all earlier versions, so I'm not sure if this is an issue with `:ex_doc` or what.

For example, I'd expect to find docs for the `CSV` module at `https://hexdocs.pm/csv/3.0.1/CSV.html`, but that page is missing. The corresponding page for `v3.0.0` is present at `https://hexdocs.pm/csv/3.0.0/CSV.html`.

**Comment by beatrichartz** [comment]
Thanks! It's curious, the API reference seems to be missing, and publishing it again does not make a difference. There's also no doc changes from 3.0.0 to 3.0.1 so I'll have to check with people running hexdocs.

**Comment by jamesvl** [comment]
Minor, but also related to the documentation: the [Upgrading from 2.x](https://hexdocs.pm/csv/3.0.0/readme.html#upgrading-from-2-x) section of the docs name the `:trim_fields` option, but it should in fact be `:strip_fields`

(The README file and [2.5.x docs](https://hexdocs.pm/csv/2.5.0/CSV.html#decode/2) both show it as `:strip_fields`)

**Comment by beatrichartz** [comment]
Ok so I figured out that `ex_doc` isn't working with elixir 1.10.x anymore which I was using to build the docs locally to publish them. Fixed that and now both `3.0.1` and `3.0.2` have module documentation again.
