### ISSUE TITLE
Takes way too long for large files

### ISSUE THREAD

**Issue by leifg** [beatrichartz/csv#18]
Maybe I'm using the library wrong but I noticed something strange. I have a large csv file (~ 500MB). With streams it is very easy to output this file line by line with a very low memory footprint:

```elixir
File.stream!("large.csv") |> Stream.each(&IO.inspect/1) |> Stream.run    
```

So I assumed it would be very easy to plug the CSV decoder in between:

```elixir
File.stream!("large.csv") |> CSV.decode |> Stream.each(&IO.inspect/1) |> Stream.run    
```

I assumed this would print out the elixir data structures that csv emits but it turns out, there is some kind of eager functionality in between because when I run this, there is no output at first and only after a while the output is shown (and much slower). Also the memory usage goes through the roof, running that code.

Is there something I'm missing?

Thinking about that, wouldn't it be best to have the possibility to provide some kind of fallback to the decode method to run side effects?

```elixir
File.stream!("large.csv") |> CSV.decode(&IO.inspect/1)
```

**Comment by beatrichartz** [comment]
This seems to be due to latest changes / bugfixes in the library - the process queue gets filled up with rows and crawls to a halt, that's also why you see the memory increase. I will try and fix it tomorrow and install some performance specs so this won't happen again. Thanks for reporting!

**Comment by beatrichartz** [comment]
This is fixed in `1.2.0` (`1.1.5` if you're using elixir < `1.1.0`) - memory is stable on my machine. Let me know if you run into something else - thanks again for letting me know.

**Comment by beatrichartz** [comment]
Ps you can run benchmarks against csv and other csv libraries using MIX_ENV=bench mix bench, which will run https://github.com/beatrichartz/csv/blob/master/bench/parse_bench.exs - a benchmark file and separators can be provided via env.

**Comment by leifg** [comment]
Just tested it with my script:

Old Version: canceled run after 3 days.
New Version: 3 minutes

Great Job

**Comment by beatrichartz** [comment]
Good to hear!
