### ISSUE TITLE
1.2.1 documentation absent from hexdocs.pm

### ISSUE THREAD

**Issue by mannyeh** [beatrichartz/csv#22]
[1.2.0](http://hexdocs.pm/csv/1.2.0/) is fine
[1.2.1](http://hexdocs.pm/csv/1.2.1/) is not a thing

**Comment by beatrichartz** [comment]
Will upload them tonight, thanks

**Comment by beatrichartz** [comment]
See https://github.com/hexpm/hex_web/issues/179

**Comment by mannyeh** [comment]
'ta, appreciated - thanks for the great module, too :)

**Comment by beatrichartz** [comment]
It's up now, closing this.
