### ISSUE TITLE
Decoder uses number of schedulers at compile time, rather than runtime

### ISSUE THREAD

**Issue by knewter** [beatrichartz/csv#24]
https://github.com/beatrichartz/csv/blob/master/lib/csv/decoder.ex#L13

This tells the decoder to use the number of schedulers that were present at compile time.  This is irrelevant to runtime.  If I were to roll a release from a small machine and deploy on a large machine, it wouldn't use the resources as well as you're trying to.

It's not hugely important, but it struck me as incorrect.  Hope this isn't a bothersome thing to bring up! :)

**Comment by beatrichartz** [comment]
Great catch, thanks for bringing this up!

I fixed this in `1.2.2`, along with some syntax updates for Elixir 1.2.
