### ISSUE TITLE
Make decode return errors in a tuple and decode! raise errors

### ISSUE THREAD

**Issue by beatrichartz** [beatrichartz/csv#28]
The decoder interface could be separated into a method raising errors and into another returning them in a tuple with the result:

```elixir
myfile
|> File.stream!
|> CSV.decode! # potentially raises errors

myfile
|> File.stream!
|> CSV.decode # returns rows as { :ok, row } and errors as { :error, "Error message" }
```

**Comment by kiliancs** [comment]
@beatrichartz I'd be happy to help with this.

Just to clarify, you are thinking CSV.decode should always return a list like below?
```
CSV.decode(stream)
[{ :ok, row }, { :ok, row }]

CSV.decode(stream)
[{ :error, error_message }, { :ok, error_message }]
```

What is the case for this vs the more common return value of `{ :ok, rows }` and `{ :error, message }`?

**Comment by beatrichartz** [comment]
Hi @kiliancs great, thanks for offering!

The reason why it should return 

```Elixir
CSV.decode(stream)
[{ :ok, row }, { :ok, row }]

CSV.decode(stream)
[{ :error, error_message }, { :ok, error_message }]
```
Is that because decode emits a stream, there is no final `rows` result, so `:ok` and `:error` have to be returned on a per-row basis.
I'll be glad to help with any questions you might have!

**Comment by kiliancs** [comment]
@beatrichartz Thanks for your clarification.

What about errors that might occur outside of the context of a row? For example I noticed an empty stream will raise a `CSV.Lexer.EncodingError`.

I worked on this a little already and I went for an API like the following, but I can always change it to wrap out-of-row errors in a list as if they were the only row, and always return a list, but that would feel a little strange, in my opinion.
```
> Stream.map([], &(&1)) |> CSV.decode!
  (raises a CSV.Lexer.EncodingError)

> Stream.map([], &(&1)) |> CSV.decode
  { :error, CSV.Lexer.EncodingError, ... }

> Stream.map(["a,b","c,d"], &(&1)) |> CSV.decode!
  [ ["a", "b], ["b", "c"] ]

> Stream.map(["a,b","c,d"], &(&1)) |> CSV.decode
  { :ok, [ ok: ["a", "b] }, ok: ["b", "c"] ] }

> Stream.map(["a,b","c,d,e"], &(&1)) |> CSV.decode!
 (raises RowLengthError)

> Stream.map(["a,b","c,d"], &(&1)) |> CSV.decode
  { :ok, [ ok: ["a", "b] }, { :error, RowLengthError ... } ] }
```
You could use it like this:
```
def handle_stream(stream) do
  with { :ok, rows } <-  stream |> CSV.decode do: handle_rows(rows)
end

def handle_row({ :ok, data }) do
  ....
end
def handle_row({ :error, ... }) do
  ...
end
```
I can prepare a PR with my code after this question is resolved.

**Comment by beatrichartz** [comment]
The empty stream case is interesting @kiliancs - I think one of the characteristics of the decode API should be that it emits a stream itself, making it possible to use it as part of a pipe. As a consequence an empty stream should emit another empty stream. So that is a bug in the current API, I pushed a fix to master. Thanks for noticing!

So, both `decode` and `decode!` should emit a transformed stream in my opinion, with errors raised / returned at the row level, so the API would be:

```elixir
Stream.map(["a,b","c,d"], &(&1)) |> CSV.decode |> Enum.into([])
# produces [ { ok: ["a", "b] }, { ok: ["b", "c"] } ]
```
