### ISSUE TITLE
Implement advanced decoding for Decoder

### ISSUE THREAD

**Issue by beatrichartz** [beatrichartz/csv#3]
The Decoder should allow to decode cells further into other types than strings. The exact mechanism still needs to be selected.

**Comment by kiliancs** [comment]
Just to get the conversation started, and maybe on the creative side, `decode` to accept a `types` option. This way we can pass a list of modules that implement a certain protocol (not sure if there's an existing one that could be used or if a new one is necessary).
```
... |> CSV.decode(types: [String, Integer, Json])
```

Alternatively, a function could be passed:
```
... |> CSV.decode(types: [String, &(Integer.parse(&1, 2)), Json])
```

The idea comes to mind to allow including that information in the `headers` option:
```
... |> CSV.decode(headers: [h1: String, h2: Integer, h3: Json])
```

**Comment by beatrichartz** [comment]
The types option is a great idea - it'd be the right choice to make this about encoding types for individual fields. Allowing functions to be passed in the option there is another great idea.

I wouldn't tie it to the headers - I can see there is some semantic value there, but it also would make the API less flexible.

Regarding naming of the option, using `field_decoders` instead of `types` would probably make the intent a bit clearer.

Regarding the protocol, I'm not sure if there is one we could reuse either. I had a quick look and found no obvious candidate. I think field decoders should take a `String` and emit a 2-tuple which then gets passed on into the stream. This would allow us to nicely streamline the output for `decode` and even raise field decoding errors for `decode!`

**Comment by mtarnovan** [comment]
How about passing the headers as a map of strings to either atoms or tuples of atoms and functions, something like this:

```elixir
%{
  "fooBar" => :foobar
  "somethingElse" => {:something_else, &__MODULE__.parse_something_else/1}
}
```

We used something like this with:

```elixir
      |> CSV.decode(headers: true)
      |> Stream.map(&(convert_fields(&1, @headers_map)))
```

and:

```elixir
  def convert_fields(row, map) do
    row
    |> Enum.map(fn {key,val}->
        case Map.get(map, key) do
          nil -> {key,val}
          {field_atom, converter} -> {field_atom, converter.(val)}
          field_atom -> {field_atom, val}
        end
      end)
    |> Enum.reduce(%{}, fn
        {key, val}, acc when is_atom(key) -> Map.put(acc, key, val)
        {_, _}, acc -> acc
       end)
  end
```

Maybe this can be generalized into something useful.

**Comment by beatrichartz** [comment]
Closing this as additional extraction can be piped onto the stream processing quite conveniently.
