### ISSUE TITLE
if multiple options are specified, then strip_cells is ignored 

### ISSUE THREAD

**Issue by tomjoro** [beatrichartz/csv#30]
When specifying headers and strip_cells, then strip_cells was ignored. I changed it to be consistent with the way Lex works, etc., by checking if the option is set.

```File.stream!("data/user_1/data.csv") |> CSV.decode(strip_cells: true, headers: true) |> Enum.each(fn(row) -> IO.inspect(row) end)```

**Comment by beatrichartz** [comment]
Released in `1.3.2`
