### ISSUE TITLE
First row skipped when parsing StringIO

### ISSUE THREAD

**Issue by moxley** [beatrichartz/csv#39]
I'm trying to parse a CSV string, using `StringIO.open/1` and `IO.binstream/1` to convert the string to a stream first. When the `:headers` option is false, the decoder skips the first row in the CSV. When `:headers` is true, the CSV is decoded as expected.

Add this test to test/csv_test.exs:
```elixir
  test "decodes from StringIO stream" do
    {:ok, out} =
      "a,b,c\nd,e,f"
      |> StringIO.open

    stream = out |> IO.binstream(:line)

    assert stream |> CSV.decode! |> Enum.map(&(&1)) == [~w(a b c), ~w(d e f)]
  end
```

Fails with:
```
  1) test decodes from StringIO stream (CSVTest)
     test/csv_test.exs:30
     Assertion with == failed
     code: stream |> CSV.decode!() |> Enum.map(&(&1)) == [~w"a b c", ~w"d e f"]
     lhs:  [["d", "e", "f"]]
     rhs:  [["a", "b", "c"], ["d", "e", "f"]]
     stacktrace:
       test/csv_test.exs:37
```

I spent quite a bit of time digging into the code and debugging, but I'm out of time. The thing that looks suspicious is the `Enum.take(1)` call in `CSV.Decoder.get_first_row/2`. It would seem to me that you can't pluck an item out of a stream like that without disturbing the stream. 

But then again, if the stream comes from a file, it's not a problem. For files, maybe the stream is opened (?) twice? For example with a file stream, you can inspect the stream, then send it to the decoder without creating a new stream:

```elixir
IO.puts "stream: #{stream |> Enum.map(&(&1)) |> inspect}"
assert stream |> CSV.decode! |> Enum.map(&(&1)) == [~w(a b c), ~w(d e f)]
```

But with a stream created from StringIO.open and  IO.bitstream, you can't inspect the stream before sending it to the decoder. The decoder outputs an empty stream.

I don't know if this is a bug in CSV, or a bug in StringIO or IO.binstream, or if I'm just doing it wrong. How does one reliably decode a CSV string? I like to do this in tests a lot. Fortunately, I've been using `headers: true`, but sometimes I'd like to have `headers: false`.

**Comment by beatrichartz** [comment]
Thanks for raising this! I'll have a chance on the weekend to look at this, seems to be related to https://github.com/beatrichartz/csv/issues/35

**Comment by beatrichartz** [comment]
Fixed in release 1.4.1 - master is on 2.0 and has to catch up yet, I'll get to that later.

**Comment by moxley** [comment]
Thank you!

**Comment by beatrichartz** [comment]
master has caught up as well if you want to use the new API
