### ISSUE TITLE
Accept string input

### ISSUE THREAD

**Issue by benwilson512** [beatrichartz/csv#40]
Does this library accept a simple string input? Sometimes the entire csv string already exists in memory and it would be nice to simply pass it into this library.

**Comment by beatrichartz** [comment]
Hey @benwilson512 thanks for asking you could use [StringIO](http://elixir-lang.org/docs/stable/elixir/StringIO.html) however there seem to be some limitations with that (see #39). I'll have a chance to look at these this we.

**Comment by beatrichartz** [comment]
Some issues in https://github.com/beatrichartz/csv/issues/39 have been addressed and released in `1.4.1` - let me know if that works for you! Feel free to reopen if there are issues left.

**Comment by jeznag** [comment]
I'm confused as to how to use this.

I'm doing:
```
    StringIO.open(csv_data_without_rubbish_at_start)
    |> CSV.decode()
    |> Enum.each(fn(row) -> 
      IO.inspect row
    end)
```

I get:
```
protocol Enumerable not implemented for {:ok, #PID<0.2450.0>}. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
```

**Comment by benwilson512** [comment]
@jeznag the return value of `StringIO.open` is `{:ok, pid}`. A full working example would be:

```
{:ok, pid} = StringIO.open("1\n2\n")
pid
|> IO.stream(:line)
|> Enum.to_list #=> ["1\n", "2\n"]
```

**Comment by jeznag** [comment]
Ok. I also just found https://github.com/beatrichartz/csv/issues/23

```
    String.split(csv_data_without_rubbish_at_start, "\n")
    |> CSV.decode
```
seems to work
