### ISSUE TITLE
Too many processes

### ISSUE THREAD

**Issue by emerleite** [beatrichartz/csv#41]
I'm processing a large number os CSV files, around 105GB. 30 minutes after started, it reach "Too many process", even if I configure ELIXIR_ERL_OPTIONS="+P 134217727".

The only way I can fix it is changing num_workers to 1. I guess it not ending finished processes.

**Comment by beatrichartz** [comment]
Interesting, thanks for raising this!

What version of elixir are you using with which version of CSV?

Also, is this 105 GB in one file or across many sma files?

Thanks!

**Comment by beatrichartz** [comment]
Found processes leaking in the workers - I released a fix in 1.4.2 . Can you let me know if this fixes the problem for you? Thanks.

**Comment by emerleite** [comment]
Hi @beatrichartz thanks. There are small files and big ones, but nothing like 10GB of single file :)

I'll test 1.4.2 now

**Comment by emerleite** [comment]
@beatrichartz Processed 105GB of CSV and everything went fine. Thanks ;)

**Comment by beatrichartz** [comment]
Great to hear, thanks again for raising this issue!
