### ISSUE TITLE
Allow stray quotes in unescaped fields

### ISSUE THREAD

**Issue by beatrichartz** [beatrichartz/csv#44]
Quotes escaping is a recommendation in RFC 4180, however CSV should allow stray quotes in fields not starting with a quote.

That means this should be valid:

```
A,B"C,D
```

Whereas this should still not be valid:

```
A,"B"C",D
```

**Comment by beatrichartz** [comment]
Not valid as per RFC, and nobody seems interested in this.

**Comment by alex88** [comment]
Just had this exact issue in a file generated by a legacy system, since this issue is quite old, is there a workaround for non?
