### ISSUE TITLE
Extract escaping function to somewhere reusable

### ISSUE THREAD

**Issue by hackling** [beatrichartz/csv#49]
https://github.com/beatrichartz/csv/blob/master/lib/csv/encode.ex#L54-L59

```
  defp escape(cell) do
    cell |>
      String.replace(<< @newline :: utf8 >>, "\\n") |>
      String.replace(<< @carriage_return :: utf8 >>, "\\r") |>
      String.replace("\t", "\\t")
  end
```

Perhaps this function could be moved to somewhere else so that the escaping logic can be used in custom encode implementations.

**Comment by beatrichartz** [comment]
This is interesting - could you outline an example usage?

**Comment by beatrichartz** [comment]
Escaping has been removed as it is not necessary for encoding.
