### ISSUE TITLE
Question (ErlangError) erlang error: :no_translation

### ISSUE THREAD

**Issue by lypborges** [beatrichartz/csv#53]
Hi, thanks for this project 👍 . Has been a big help for beginners like me.I'm getting a strange error and have no clue how to fix it. 

I only get this error if I try do encode this field "Hotel 10 Aparecida de Goiânia" without it works just fine. Do you have any tip or direction to give me?

> table_data |> CSV.encode |> Enum.each(&IO.write(file, &1))
** (ErlangError) erlang error: :no_translation
    (stdlib) :io.put_chars(#PID<0.248.0>, :unicode, "27,SinnPDV Atualização Goiânia,6125,Hotel 10 Aparecida de Goiânia,Felipe Borges Ferreira,Bruno\r\n")
    (elixir) lib/enum.ex:657: anonymous fn/3 in Enum.each/2
    (elixir) lib/enum.ex:1637: anonymous fn/3 in Enum.reduce/3
    (elixir) lib/enum.ex:2843: Enumerable.List.reduce/3
    (elixir) lib/stream.ex:769: Stream.do_list_transform/9
    (elixir) lib/enum.ex:1636: Enum.reduce/3
    (elixir) lib/enum.ex:656: Enum.each/2

**Comment by beatrichartz** [comment]
This error occurs in `IO.write` - the line is already encoded at that point:

```elixir
"27,SinnPDV Atualização Goiânia,6125,Hotel 10 Aparecida de Goiânia,Felipe Borges Ferreira,Bruno\r\n"
```

Is the file stored in the `file` variable opened with the [`:utf8` mode](http://elixir-lang.org/docs/stable/elixir/File.html#open/2)? It might be that it is opened at ASCII and erlang fails to translate the chars outside the ASCII range.

**Comment by beatrichartz** [comment]
Just noticed, the README does not advertise this correctly. I updated it there. Thanks for raising!

**Comment by lypborges** [comment]
Thanks a lot. Just chage:

`file = File.open!("deals.csv", [:write])`
to 
`file = File.open!("deals.csv", [:write,:utf8])`

**Comment by beatrichartz** [comment]
Great, thanks for letting me know!
