### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by simonh1000** [beatrichartz/csv#54]
Hi, I downloaded installed and started using your library, but I had to give up when I could work out how to pattern match on a row in order to do a database insert. I've solved it with another library, but thought it worth recommending you beef up the example for beginners like me.

**Comment by beatrichartz** [comment]
Interesting - can you elaborate or post some example code you tried and the code that solved it with the other library so I can create an appropriate example?

Thanks!

**Comment by simonh1000** [comment]
Sure
```
CSVLixir.read("ignore/customers.csv")
|> Enum.to_list
|> Enum.each( fn([id, nm, csr, sal]) ->
        Customer.changeset(%Customer{},
            %{masterid: id,
              custname: nm,
              csrid: String.to_integer(csr),
              salesid: String.to_integer(sal)})
        |> Repo.insert
    end)
```

**Comment by beatrichartz** [comment]
Depending on the version you use and assuming the file contains no headers, these are the solutions I can think of:

v1.4.x
```elixir
File.stream!("ignore/customers.csv")
|> CSV.decode
|> Enum.each(fn([id, nm, csr, sal]) ->
        Customer.changeset(%Customer{},
            %{masterid: id,
              custname: nm,
              csrid: String.to_integer(csr),
              salesid: String.to_integer(sal)})
        |> Repo.insert
end)
```

Latest master:
```elixir
File.stream!("ignore/customers.csv")
|> CSV.decode
|> Enum.each(fn
        {:ok, [id, nm, csr, sal]} ->
            Customer.changeset(%Customer{},
                %{masterid: id,
                  custname: nm,
                  csrid: String.to_integer(csr),
                  salesid: String.to_integer(sal)})
            |> Repo.insert
         {:error, message} ->
            # Whatever you want to do with invalid rows
end)
```

**Comment by simonh1000** [comment]
How annoying - i'm sure I tried that. I only needed csv to copy across a database so absolute performance is not a necessity, so I'm going to stick with what i had. But I would recommend you add something like this to the README

**Comment by hopewise** [comment]
Hi,

As I've read the latest sample code above, I see that `Enum.each` is used, however, I read in the elixir docs:

`Note that the functions in the Enum module are eager: they always start the enumeration of the given enumerable. The Stream module allows lazy enumeration of enumerables and provides infinite streams.`

So, why not use `Stream` instead of `Enum` to iterate through the output of `CSV.decode`?

**Comment by beatrichartz** [comment]
@hopewise `CSV.decode` works with streams, but at some point you want to start enumeration, otherwise the stream will never be run. This is why you are using `Enum.each`, which is roughly equivalent to doing `Stream.each ... |> Stream.run`
