### ISSUE TITLE
Explicit Ordering of Headers

### ISSUE THREAD

**Issue by StevenXL** [beatrichartz/csv#57]
Provide the ability for the client to decide the ordering of the headers. 

**Current Behavior**: When headers are provided, the final output orders the headers in alphabetical order. 

**Desired Behavior**: When headers are provided as a list in the options to `CSV.Encoding.Encoder.encode/2`, the headers in the final output should be ordered as in the list.

**Comment by beatrichartz** [comment]
Nice suggestion, thanks for that!

**Comment by beatrichartz** [comment]
This should already be the case for latest master and latest v1 - can you verify? Feel free to reopen with a bug report if for some reason this is not the case when you're using `CSV`
