### ISSUE TITLE
Running in production/release slow

### ISSUE THREAD

**Issue by jakkra** [beatrichartz/csv#58]
Hi I'm having problems that 

`      
full_rows |> CSV.encode |> Enum.each(&IO.write(file, &1))
`
is realy slow, and won't write the whole data to the file.

It works very well when I'm running mix phenix.server, but as release it's not working well.

I have consolidate_protocols: true in mix.exs

Any idea what it might be?

**Comment by beatrichartz** [comment]
There might be different reasons for this - when you are saying release, does this mean the code is running on a different machine? If so, it might be that io on that machine is just slower, that the input is different, etc. What does slow / not working well mean (e.g. does it take seconds to write one row? / does the encoding stall? / etc. ) ?

You might want to try the following:

```elixir
full_rows |> CSV.encode |> Stream.run
```

To verify that encoding is causing the operation to be slow. If so, it would be brilliant if you could post an example of your input so we can get to the bottom of this.

**Comment by jakkra** [comment]
Will get back to you, away for a few days.
