### ISSUE TITLE
How to get the count number of rows in the CSV file?

### ISSUE THREAD

**Issue by hopewise** [beatrichartz/csv#64]
How to get the count number of rows in the CSV file? Also, would you please have a look here: https://elixirforum.com/t/inserting-csv-into-postgres/3606

**Comment by beatrichartz** [comment]
You can get the number of rows by appending `Enum.count` to your stream, e.g. `CSV.decode ... |> Enum.count`. Regarding your forum post, I would not worry about your database getting overwhelmed with queries: As long as they are executed synchronously and linearly, there will only ever be one write query at a time which is handled quite well by most databases.

**Comment by hopewise** [comment]
Thanks, but if I assume it will take 0.5 second to insert a record in db server within the same local area network, what if I have 20000 entry? = 10000 seconds, about 2.5 hours to complete..

Can't I benefit from concurrency of Elixir? what's your advice?

**Comment by beatrichartz** [comment]
500ms for an insert sounds like a lot of time for an insert on a LAN to me, but I can't possibly comment on your setup. My advice at this point can only be to avoid premature optimisation.
