### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by PragTob** [beatrichartz/csv#66]
Hi there,

thank you for this nice library!

It hasn't seen a release in quite some time and some of the new features on master are pretty nice and we'd like to use them, so a new release would be highly appreciated :)

Thanks!
Tobi

**Comment by beatrichartz** [comment]
Some concepts in master need a bit of thought before releasing, mainly the rows preprocessing. Other than that it's good to go. Out of interest, what are the particular features you are looking forward to using? It's always good to get some insight into how the library is used by others.

**Comment by PragTob** [comment]
What my co worker told me was that apparently in the last released version apparently the library just crashes on invalid CSV (no idea what sort of invalid he test it with sorry) while master can somehow work with that :)

Thanks

**Comment by beatrichartz** [comment]
@PragTob There is a 2.0.0 release candidate available now. I'd be very interested to hear a bit more about how you're using this library and whether the changes in this rc are making your lives easier. The crash v non-crash description tells to me that you are using the parsing with inlined errors, which is new. There are still some errors that will raise errors though, particularly when escape sequences are not finished. There are some possible solutions for this to be inlined as well, it would be good though to have some more opinions on how this should be done, hence your our your colleagues input would be very welcome.

**Comment by beatrichartz** [comment]
@PragTob 2.0.0 is out the door. Your colleague might be interested in [`decode`](https://hexdocs.pm/csv/CSV.html#decode/2) vs [`decode!`](https://hexdocs.pm/csv/CSV.html#decode!/2). The former will inline all errors into the stream now, whereas the latter raises them same as before.

**Comment by PragTob** [comment]
@beatrichartz thanks a lot :) We haven't worked on the application since, but once we get to it we'll definitely update and then make this work. Thanks a lot!
