### ISSUE TITLE
CSV.decode(headers: true) breaks when there is more than one column with a matching header

### ISSUE THREAD

**Issue by halostatue** [beatrichartz/csv#69]
This is a subtle but important implementation problem when using a straight-up map as your target implementation, because it’s not *quite* right since keys cannot be reused.

Assume you have a CSV like this:

```csv
id,name,address,address,city,province
1,joe,123 city st,,moosejaw,SK
```

This will result in a map `%{"id" => 1, "name" => "joe", "address" => "", "city" => "moosejaw", "province" => "SK"}`. While this seems reasonable, this is completely incorrect and results in data loss. The [Ruby CSV](https://github.com/ruby/csv) library handles this correctly, in that it returns a data structure that *acts* like a hash but is not *quite* a hash so that you can ask for `row['address'] # => "123 city st"` and `row['address', 1] # => nil` (the first can be `row['address', 0]`, too).

I suspect that to fix this, you will need to return a specialized form that can be handled properly. The interface would be something like `CSV.Row.get(row, header, index \\ 0) where is_binary(header)` and `CSV.Row.get(row, index)` (because `row[3]` always returns the 4th column.

**Comment by beatrichartz** [comment]
You're correct, this is a case that is currently not handled. I wonder whether keyword lists would suffice here, although there are other limitations there: [Atoms only support latin1 up until R19, and utf8 from R20](http://erlang.org/doc/apps/stdlib/unicode_usage.html), so maybe this is a solution for the future.

Happy for this to return a specialised row in the meantime. I'll put some thought into this, pr's are also very welcome.

**Comment by halostatue** [comment]
Will give it some thought. I’m unfortunately super busy with other stuff, so don’t see being able to do anything about this for a while.
