### ISSUE TITLE
Add an option to disable the row_length check

### ISSUE THREAD

**Issue by jlgeering** [beatrichartz/csv#71]
I'm trying to process an invalid csv, with 10 headers in the first row, follow by rows with 10 _or less_ values.

decode (rightfully) fails with `Row has length 8 - expected length 10 on line X`

I could probably try to pre-process the rows and add the missing columns (append the right number of commas to the line) but that would require that I handle all the escaping cases that you already handle in your code, to be able to actually count the columns.

Probably easier (for me) would be to have an option to disable this check, maybe something like:

`row_length: false` and maybe even `row_length: 10` to enforce a certain row_lenght

would you accept such a merge request?

**Comment by beatrichartz** [comment]
@jlgeering apologies for the late reply. Sure, what about something like: `row_length: :variable` to disable it.

I'd happily accept a PR!

**Comment by Zenohate** [comment]
Since I have the very same issue, I will make a PR with it

**Comment by joecorkerton** [comment]
This feature would also be very useful for me. @beatrichartz is there any update on the status of the PR?

**Comment by Zenohate** [comment]
In the worst case, you can use the version from my repo @
https://github.com/Zenohate/csv

Le jeu. 24 mai 2018 16:52, Joe Corkerton <notifications@github.com> a
écrit :

**Comment by KernelMadness** [comment]
Hi guys, hi @beatrichartz. Any chance to get this merged?

**Comment by beatrichartz** [comment]
@KernelMadness @vladimir-e @Zenohate thanks for your input, this has been merged in `2.2.0` with a `validate_row_length: false` option for decoding.
