### ISSUE TITLE
Crashes on unrecognized letters?

### ISSUE THREAD

**Issue by houshuang** [beatrichartz/csv#8]
Here are two examples of individual lines that led the parser to barf and stop:

```csv
frações,1,M,12-Sep,,,,,,,,,,,,,,,,,,,
```

```csv
matemática financeira,1,M,12-Sep,,,,,,,,,,,,,,,,,,,
```

This is in a file generated by Excel (export as XLS). Not sure what format it was in - saving it in Vim as UTF-8 resolved the issue. However, it seems like it could either accept parsing a file, even if some characters are messed up, or at least give a useful error message ("Non UTF-8 valid character found on line x etc").

Error message:
```elixir
17:41:09.397 [error] Error in process <0.112.0> with exit value: {function_clause,[{'Elixir.CSV.Lexer',lex,[411,<<37 bytes>>,<0.120.0>,{content,<<5 bytes>>},44],[{file,"lib/csv/lexer.ex"},{line,35}]},{'Elixir.CSV.Lexer',lex_into,2,[{file,"lib/csv/lexer.ex"},{line,24}]}]}
```

**Comment by beatrichartz** [comment]
Yes, more helpful errors in these would be good - I'll investigate a solution in the next days.

Thanks!

**Comment by beatrichartz** [comment]
Done - release 1.1 will produce better error messages including line numbers for invalid encodings.

**Comment by houshuang** [comment]
:+1:
