### ISSUE TITLE
Suggested strategy for very large file?

### ISSUE THREAD

**Issue by bcalco** [beatrichartz/csv#80]
`File.stream!(huge_csv_file) |> CSV.decode(headers: true, num_workers: 8) |> Enum.to_list` causes ERL VM to crash generating a 25 GB crash dump file. The `huge_csv_file` is roughly 6.5GB in size.

Clearly, I need to figure out a better way to deal with this data. Any suggestions for working with huge files?

**Comment by alco** [comment]
@bcalco You asked it to load the whole file into memory by calling `Enum.to_list`. Perhaps, there's a better way to handle that huge CSV file in your case. What do you intend to do with it?

**Comment by beatrichartz** [comment]
As @alco said this is due to the list being created in memory, nothing we can change. I'd suggest to continue working on the stream rather than trying to load it all into memory.
