### ISSUE TITLE
Missing documentation for option headers in CSV.encode

### ISSUE THREAD

**Issue by h4cc** [beatrichartz/csv#84]
I cant find documentation for `headers: true` or `headers: [...]` at CSV.encode

Source: https://github.com/beatrichartz/csv/blob/master/lib/csv.ex#L233

**Comment by beatrichartz** [comment]
Hey @h4cc sorry for the late reply. Encode is currently very simple and only takes lists as input. A header list can be passed as the first row. We could add an option to be able to pass maps to encode and produce a header row for the first map passed, is that what you had in mind at the time?

**Comment by h4cc** [comment]
I think this was just a hint for a missing documentation back then. Thanks!
