### ISSUE TITLE
Tabs within cells?

### ISSUE THREAD

**Issue by darksheik** [beatrichartz/csv#86]
I have a case where I have a comma-delimited file, but one of the fields within is tab-separated.

I'm doing something like this:
```
full_field = ["12345", "67890"]
|> Enum.join("\t")
```

Doing an `IO.puts` in `iex` will successfully render the tab:

```
full_field = ["12345", "67890"] |> Enum.join("\t")
"12345\t67890"

IO.puts v()
12345   67890
```

But in the file it stays as a `\t`.  Is there a trick I can be using to ensure a tab character gets to the file?

**Comment by beatrichartz** [comment]
Hi there, apologies for the late reply - did you get around to solving this? Not quite sure how it relates to the `CSV` library, could you expand your question?

**Comment by beatrichartz** [comment]
Closing this, feel free to reopen if help is still needed.
