### ISSUE TITLE
`CSV.encode` seems extremely slow

### ISSUE THREAD

**Issue by myronmarston** [beatrichartz/csv#9]
``` elixir
defmodule CSVTest do
  use ExUnit.Case, async: true

  for rows <- [1, 10, 100, 500] do
    @rows rows
    test "generating #{rows} rows" do
      data = List.duplicate([1, 2, 3, 4, 5], @rows)
      data |> CSV.encode |> Stream.run
    end
  end
end
```

```
➜ mix test test/csv_test.exs --trace

CSVTest
  * generating 100 rows (1858.3ms)
  * generating 1 rows (16.4ms)
  * generating 10 rows (173.0ms)
  * generating 500 rows (8899.1ms)


Finished in 10.9 seconds (0.05s on load, 10.9s on tests)
4 tests, 0 failures
```

It appears to be linear in the number of rows (as you'd expect) but with a huge constant factor -- about 17ms per row.

Any idea why the encoder is so slow?

**Comment by beatrichartz** [comment]
`CSV.encode` works with the [`CSV.encode`](http://hexdocs.pm/csv/1.0.0/CSV.Encode.html) protocol which has `@fallback_to_any` enabled. The only provided implementation apart from the default one at this point is for `BitString`, so your test falls back to the default implementation of the protocol for every cell it needs to encode, which is rather costly.

If you provide an implementation to encode integers, your numbers should drop drastically:

```elixir
defimpl CSV.Encode, for: Integer do
  def encode(data, env \\ []) do
    data |> to_string |> CSV.Encode.encode(env)
  end
end
```

I opened a new issue https://github.com/beatrichartz/csv/issues/10 to provide default implementations (apart from string) where appropriate in future versions - I'd happily accept a PR on this.

**Comment by myronmarston** [comment]
Thanks for the quick response.  I'm new to elixir and haven't implemented any protocols yet.  Given that the implementation for `Any` is _identical_ to the implementation you pasted for `Integer`, why is it so slow?  That's extremely surprising to me.

More generally, the README talks up the speed of this library (although re-reading it now, I'm seeing it only mentions the speed of parsing, not encoding), and it seems odd for it to require users to implement a protocol for primitive types to get decent performance.  I saw the note about polymorphic encoding but thought it was just necessary for custom types, and not essential.

Given how slow the `Any` implementation is, does it make sense to provide it at all?  If the library requires that you implement a protocol to get decent performance I'd rather it fail and tell me "implement this protocol" rather than just going really slow with no indication that there's something you can do to address the slowness.

**Comment by beatrichartz** [comment]
I dug a bit deeper on this since this was surprising to me as well - I found protocol dispatch can be sped up considerably without adding particular types by consolidating protocols, which as of 1.0.4 can be enabled by adding `consolidate_protocols: true` to your mix.exs project description. Here's the corresponding blog post: http://blog.plataformatec.com.br/2015/04/build-embedded-and-start-permanent-in-elixir-1-0-4

On my machine, this leads to very good performance without a specific implementation of the protocol for `Integer` in place.

I added relevant documentation to the README, thanks so much for reporting!

**Comment by myronmarston** [comment]
Thanks.  I added the `consolidate_protocols: true` option and confirmed that it makes an emormous difference in performance.

**Comment by justgage** [comment]
This is still kind of a problem, we ended up creating default implementations for floats, atoms, and ints in our code to avoid this.

**Comment by beatrichartz** [comment]
@justgage thanks for raising this, is this a problem even if you have protocol consolidation in place as suggested above? I'd be interested to see the performance difference you are seeing with your default implementations vs without them.

**Comment by justgage** [comment]
@beatrichartz I'm not sure, we tried putting it in our `mix.exs` with no apparent effect, however things do seem much faster when we ran things in a `iex` session so perhaps elixir kind of chooses when do the `protocol consolidation`? Maybe it would never happen in prod mode? Either way we kind of just wanted it to perform the same no matter what to avoid confusion.

**Comment by beatrichartz** [comment]
@justgage if I understand correctly, the performance when running in `iex` is fine, but in other places it is not? If so, could you provide an example of in what execution environment performance doesn't match expectations?

**Comment by justgage** [comment]
@beatrichartz We found, in particular, running it in a mix task was very slow.

**Comment by cheerfulstoic** [comment]
I have the same issue.  My code is in a mix task, but when I startup `iex -S mix` and run `Mix.Tasks.SequentializeCsv.run(["thefile.csv"])` it is much, much faster.

I found #58 as well and I tried using `Stream.run` and found that it just sat there spinning for a long time.

**Comment by cheerfulstoic** [comment]
I also tried setting `consolidate_protocols: true` in my `mix.exs` as suggested by the `README`, though it wasn't completely clear where I should put it (inside `def project`?)  I found one post referencing `Mix.Project.config[:consolidate_protocols]` so I outputted that and saw that it was `true` (even without changing my `mix.exs`)

**Comment by lkuty** [comment]
Same here. It was slow (+-200s instead of +-400ms, 600 rows 574 cols) with consolidated protocols and fast with more protocol implementations. See https://elixirforum.com/t/library-for-exporting-csv/14346/3
I used:
```elixir
defimpl CSV.Encode, for: Integer do
  def encode(data, _env \\ []) do
    data |> Integer.to_string
  end
end
defimpl CSV.Encode, for: Float do
  def encode(data, _env \\ []) do
    data |> Float.to_string
  end
end
defimpl CSV.Encode, for: Atom do
  def encode(data, env \\ [])
  def encode(true, _env), do: "1"
  def encode(false, _env), do: "0"
  def encode(data, _env) do
    data |> Atom.to_string
  end
end
defimpl CSV.Encode, for: DateTime do
  def encode(data, _env \\ []) do
    data |> DateTime.to_string
  end
end
```
I didn't send my string into `CSV.Encode.encode(env)` as you're suggesting in one of your previous comments. I don't know if it is a problem or not for such simple type.
For DateTime, I ended up with code specific for my time zone to get local time:
```elixir
defimpl CSV.Encode, for: DateTime do
  def encode(data, _env \\ []) do
    # data |> DateTime.to_string
    data
    |> DateTime.shift_zone!("Europe/Brussels")
    |> Timex.format!("%Y-%m-%dT%H:%M:%S.%L", :strftime)
  end
end
```
I was surprised by such a slow default behaviour. IMHO we should have a sensible default implementation for simple types. I also understand that this way of doing things allows us (or force us) to customize the implementation to our needs. But I didn't know that.
